userRoutes
bcantello/GA-Project-3-Backend pull request #21
Opened 2020-04-18 04:11 UTC by ScottBeverly

2020-04-18 16:15 UTC, bcantello requested changes

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +
Add a getProviderById function. Id is more unique than name so I imagine we will want to use that whenever possible.

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +const getAllProviders = (req, res) =>{
nit: add space after end of fat arrow. Some of your functions have a space, some don't. Should be consistent. Let's do spaces for all.

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +const createProvider = (req, res) =>{
nit: space after fat arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +        })
Is this all necessary? Looks like the create function got blended with an update function?

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +const updateProvider = (req, res) =>{
nit: white space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +    Provider.findOneAndUpdate({_id: req.params.id}, body).then((provider =>{
nit: white space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/providerController.js
> +
nit: remove extra white space

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +const getAllUsers = (req, res) =>{
nit: white space after fat arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +
Add getUserById function

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +            })
Is this necessary for a create function?

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +const createUser = (req, res) =>{
nit: space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +const updateUser = (req, res) =>{
nit: space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +    User.findOneAndUpdate({_id: req.params.id}, body).then((user =>{
nit: white space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +const deleteUser = (req, res) =>{
nit: space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +    User.findOneAndDelete({_id: req.params.id}).then((user) =>{
nit space after arrow

2020-04-18 16:15 UTC, bcantello commented on Controllers/userController.js
> +
nit: remove extra white space

2020-04-18 16:15 UTC, bcantello commented on Models/userModel.js
> +
nit: remove extra white space

2020-04-18 16:15 UTC, bcantello commented on Models/userModel.js
> +const mongoose = require('../DataBase/connection');
nit: Add white space between dependencies and functions

2020-04-18 16:15 UTC, bcantello commented on Models/userModel.js
> +    zip: Number,
We should probably include street address for the user. Provider needs to get to their house

2020-04-18 16:15 UTC, bcantello commented on Models/userModel.js
> +})
nit: space between end of function and exports

2020-04-18 16:15 UTC, bcantello commented on Models/userModel.js
> +module.exports = User;
nit: add whitespace to end of file

2020-04-18 16:15 UTC, bcantello commented on Routes/providerRoutes.js
> +
nit: remove white space. const controller is a dependency declaration

2020-04-18 16:15 UTC, bcantello commented on Routes/providerRoutes.js
> +
add get provider by Id route after created

2020-04-18 16:15 UTC, bcantello commented on Routes/userRoutes.js
> +
remove white space

2020-04-18 16:15 UTC, bcantello commented on Routes/userRoutes.js
> +
add get by id route

2020-04-18 16:15 UTC, bcantello commented on Routes/userRoutes.js
> +module.exports = router;
nit: add white space at end of file

2020-04-18 17:15 UTC, bcantello requested changes

2020-04-18 17:15 UTC, bcantello commented on Models/userModel.js
> +const UserSchema = mongoose.Schema({
Need to either instantiate a new instance of mongoose.Schema, or declare a global Schema variable.
- instantiate:  const UserSchema = new mongoose.Schema({
- declare:  const Schema = mongoose.Schema;
                   const UserSchema = new Schema({

2020-04-18 17:57 UTC, bcantello commented on Controllers/userController.js
> +
Add getUserAppointmentsByID function
We need to be able to pull all of the appointments that are relevant to a specific user.  something like:
```suggestion

const getAuthorsWithCookbooks = (req, res) => {
     Author.find({ _id: req.params.id })
     .populate("cookbooks")
     .then((authors) => {
         res.json(authors);
     });
};


```

2020-04-18 20:26 UTC, bcantello commented on Models/userModel.js
> +    zip: Number,
Also should include a key value pair for email, and one for password as well

2020-04-18 20:27 UTC, bcantello commented on Models/userModel.js
> +    ]
I think we probably need a collection for pets, with its own schema and controllers for creating, updating, and deleting pets.

2020-04-19 05:07 UTC, bcantello commented on Models/userModel.js
> +    ]
I created the Pet model, controller, and router. The pets section of the user schema should be updated to:
```suggestion
    pet: [
        {
            ref: "Pet",
            type: mongoose.Schema.Types.ObjectId
        }
    ]
```

2020-04-20 15:36 UTC, GracieEveritt approved these changes

2020-04-20 15:36 UTC, merged